### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by asafbenj** [amathislab/DLC2action#17]
I did
```
from dlc2action.project import Project
project = Project(
    'dlc_proj_2',
    data_type='dlc_track',
    annotation_type='csv',
    data_path='data_path',
    annotation_path='annotation_path',
)
project.update_parameters(
    {
        "data": {
            "data_suffix": ".pickle", # there's currently only 1 file in the folder
            "canvas_shape": [1186, 1054], 
            "annotation_suffix": ".csv", 
            "fps": 1 
        },
        "general": {
            "exclusive": True, 
        },
    }
)
project.run_default_hyperparameter_search('def_search_1st')

```
and got:
> `[I 2024-03-25 12:06:09,901] A new study created in memory with name: no-name-08bd6156-20e9-474f-acbf-9da343bb7576
> [W 2024-03-25 12:06:11,969] Trial 0 failed with parameters: {'losses/ms_tcn/alpha': 6.670201845207353e-05, 'losses/ms_tcn/focal': True, 'training/temporal_subsampling_size': 0.8767323445118085, 'model/num_f_maps': 70, 'general/len_segment': 1024} because of the following error: UnicodeDecodeError('utf-8', b'\x80\x05\x95\x1b\x02\x01\x00\x00\x00\x00\x00}...

on a Window PC running in a dedicated conda env with cuda 11 enabled GPU.
Happy to supply the files if it could help reproduce the issue. Thanks!

**Comment by andybonnetto** [comment]
This issue was solved by changing the behavior annotation data format (from csv to dlc_track (.pickle) ) as it was misunderstood what the format was supposed to be. Here is a brief description of the dlc_track data format :

The pickle data format is the original one, is compatible with the annotation GUI, and should be a tuple (not a dictionary) including the following information:
(Information dictionary, list of individuals, list of behaviors, list of annotations)
Each of them should have the following format:
 
•         Information dictionary = {“annotator” : “Asaf”, “video” : “video1”, …} You can add any information you like in here.
•         List of individuals = [“mice1”, “mice2” …], the default is [“ind0”] and you can keep that if you work with one individual to avoid unnecessary troubles. Note that the order is very important.
•         List of behaviors = [“a_01”, “a_02”, “a_03”, …]  ,note that the order is very important.
•         List of annotations = [[[[START, STOP, CONFUSION], [START, STOP, CONFUSION], ….]]]
→ If we decompose this list we have triplets for each individual, behavior annotated segment, using the order defined In list of individuals and in list of behaviors. This format might be constraining but optimizes the amount of information stored in a file.
→ CONFUSION is a float number from 0 to 1, 0 being absolute ground truth.

**Comment by andybonnetto** [comment]
This issue was solved by changing the behavior annotation data format (from csv to dlc_track (.pickle) ) as it was misunderstood what the format was supposed to be. Here is a brief description of the dlc_track data format :

The pickle data format is the original one, is compatible with the annotation GUI, and should be a tuple (not a dictionary) including the following information:
(Information dictionary, list of individuals, list of behaviors, list of annotations)
Each of them should have the following format:
 
•         Information dictionary = {“annotator” : “Asaf”, “video” : “video1”, …} You can add any information you like in here.
•         List of individuals = [“mice1”, “mice2” …], the default is [“ind0”] and you can keep that if you work with one individual to avoid unnecessary troubles. Note that the order is very important.
•         List of behaviors = [“a_01”, “a_02”, “a_03”, …]  ,note that the order is very important.
•         List of annotations = [[[[START, STOP, CONFUSION], [START, STOP, CONFUSION], ….]]]
→ If we decompose this list we have triplets for each individual, behavior annotated segment, using the order defined In list of individuals and in list of behaviors. This format might be constraining but optimizes the amount of information stored in a file.
→ CONFUSION is a float number from 0 to 1, 0 being absolute ground truth.
